### ISSUE TITLE
gzip-js dependency and is minMaxInfo needed in the core contrib?

### ISSUE THREAD

**Issue by davglass** [gruntjs/grunt-lib-contrib#5]
Is there a reason that this is sync and only writes the info?

https://github.com/gruntjs/grunt-lib-contrib/blob/master/lib/contrib.js#L80-L88

If it can be async, then you can use the native node `zlib` to do this.

The root issue is that this is a core dependency for grunt and it requires the `gzip-js` module which does not have a license attached to it. This makes it very hard for others to use grunt in a "corporate" environment with a dependency that lacks licensing information.

**Comment by cowboy** [comment]
If it were async, every task that used this code would need to be written in an asynchronous manner. Do you know of any synchronous gzip libs that have a permissive license?

**Comment by davglass** [comment]
I took a brief look but didn't see any that are sync, they all appear to be async.

Is there a reason that this is required in the core or can it be in an external module that's opt in?

**Comment by cowboy** [comment]
This isn't in the core, it's just a lib that many of our officially maintained contrib plugins use. You don't have to use any of the contrib plugins. Grunt itself is separate.

**Comment by tkellen** [comment]
Very few plugins use this bit of code, though.  Actually, until very recently, it was only in grunt-lib-legacyhelpers.  I'm not sure why it got migrated here.

**Comment by cowboy** [comment]
Note that this module is used by some plugins that are specified as Grunt dev dependencies. These plugins (and thus this module) won't be installed when using Grunt normally in a project. they'll only be installed when running `npm install` manually from within the grunt project folder, in the case of developing Grunt.

**Comment by cowboy** [comment]
Long story short though, in the future we'll be using promises all over the place and it'll be trivial to make anything async. Right now, however, it's not trivial. It'd be really great if we could find a better licensed sync gzip implementation to use here.

**Comment by davglass** [comment]
Sorry, that was my point (doing too many things at a time).

This is a sort of a "core" package that many other tools do now or will require. Currently it shows 53 dependents (https://npmjs.org/package/grunt-lib-contrib)

That means there are 53 less modules that can be used due to a license issue with one dependency.

If it's not a "core" method (as in used in all kinds of places), I would like to see that one little method moved over to a module that isn't potentially a requirement for others.

**Comment by tkellen** [comment]
This is only called in uglify/htmlmin and cssmin.  We're in the middle of releasing Grunt 0.4 (happens on Moday).  I can take care of this issue after.

**Comment by davglass** [comment]
Thanks!

**Comment by davglass** [comment]
Any update on removing the deps from this module? I'm trying to get YUI's new grunt based release system up and I can't use `grunt-contrib-compress` since it requires this module.

**Comment by tkellen** [comment]
Sorry Dav... totally swamped here.  If you can find an alternate npm module with a better license that produces the same results, I'd be happy to merge it.

**Comment by davglass** [comment]
I've been looking and I can't find a zlib compliant lib that's sync. They are all async. I've played around with a couple of hacks to stall the event loop so the built-in node zlib async functions will execute, but it's way too hacky.

Looks like I'm going to have to do something else, since this module is required by 40+ other modules they will all be unusable to us as well. (https://npmjs.org/package/grunt-lib-contrib)

Thanks for the help tho.

**Comment by tkellen** [comment]
Have you tried contacting the author about adding a license?

**Comment by tkellen** [comment]
We could try talking with @isaacs since this project seems to be abandoned?  Perhaps we can re-release it with a permissive license?  Would that be acceptable to Yahoo?  Does anyone know if that is even legal?

**Comment by davglass** [comment]
> Have you tried contacting the author about adding a license?

I emailed his personal address as well as commented on that ticket.

> We could try talking with @isaacs since this project seems to be abandoned? Perhaps we can re-release it with a permissive license? Would that be acceptable to Yahoo? Does anyone know if that is even legal?

IANAL, but I don't think that it works that way ;)

**Comment by gyehuda** [comment]
IANAL either, but I do make many of the open source and licensing related decisions in this space for Yahoo!. Dav asked me to weigh in. 

We have here an issue with code published on GitHub without a license.  By the terms of copyright law (like it or not) the author is the only person who can allow us to copy this code and use it. Many people assume (probably correctly) that people put stuff on Github to share it -- so it's like an implied license. But without an explicit license, you take a slight risk that the author accuses you of infringement for using the code he shared here. Most people are OK assuming this risk, but we at Yahoo! want to strive for a higher standard, especially in YUI where we want to be sure you are getting the best code with an assurance that we are doing this right.

You can't re-license someone else's code -- especially code that has not license stating that you could re-license it (catch-22). But you can author code that does the same thing -- and put your open source license on your code. The idea of a sync zlib module is not protected by copyright, only his specific code that implements it.  If someone implements the same function in their own code, that code could be published by the new author and used here.  Since the original author failed to license the code, and has abandoned it, we are left with a tease. It's code we want to use, but legally it incurs a risk we should not take. :-(  I hope open source developers stand by their code, and use licenses to express their willingness to share their code with others.

**Comment by shama** [comment]
I don't mind writing a sync gzip lib that is MIT licensed to replace the dep. Doesn't seem too hard (famous last words).

**Comment by davglass** [comment]
@shama That would be great, I could help if you wanted it. I just didn't have time to write a new module (and support it) just for this :)

**Comment by isaacs** [comment]
Fwiw, I don't think sync zlib in core would be too terrible. That would
probably make this whole question moot, yes? In the meantime, it could a
user land module or something.

**Comment by davglass** [comment]
@isaacs I initially thought that a sync zlib could be used (I did see a couple of compilable modules but not sure on OS support), but then I saw this thread:

https://github.com/joyent/node/issues/3128#issuecomment-5197171

That's why I was looking at a simple JS based one in user land.

**Comment by shama** [comment]
Here is where the contrib plugins use `minMaxInfo`: [grunt-contrib-htmlmin](https://github.com/gruntjs/grunt-contrib-htmlmin/blob/master/tasks/htmlmin.js#L38), [grunt-contrib-cssmin](https://github.com/gruntjs/grunt-contrib-cssmin/blob/master/tasks/cssmin.js#L34) and [grunt-lib-legacyhelpers](https://github.com/gruntjs/grunt-lib-legacyhelpers/blob/master/lib/legacyhelpers.js#L32). And soon, grunt-contrib-uglify.

The simplest route might be to just use core zlib and make htmlmin, cssmin and uglify async. Considering that promises are on the horizon; upstreaming a sync zlib might not be worth the effort.

@cowboy @tkellen Let me know. I can update the plugins and this lib. Otherwise I'll hash out a simple sync gzip lib. FWIW, a decent browserified zlib is on my co-worker's todo list for voxel.js. That could become the starting point for it.

**Comment by shama** [comment]
Actually scratch all that. I found [zlib-browserify](https://github.com/brianloveswords/zlib-browserify) which is a wrapper for [imaya/zlib](https://github.com/imaya/zlib.js). They are MIT licensed and it has `gzipSync`.

@davglass @gyehuda Would using that lib instead put you guys in the clear?

**Comment by davglass** [comment]
If it & it's deps are all MIT we would be good.

**Comment by pdsarin** [comment]
Just upgraded to grunt 0.4 over the weekend from 0.3, and I noticed that the uglify and cssmin tasks are a lot slower than their 0.3 counterparts. Could this change be the reason why? [This pull request](https://github.com/gruntjs/grunt-contrib-uglify/pull/35) makes me think it might be.

Really just looking for advice on how to proceed. I could just send a PR for grunt-contrib-cssmin that makes reporting configurable.
